### PR TITLE
summary of Code Review in the Lab post

### PR DESCRIPTION
**Pull request by stefaniebutland**

### CODE REVIEW

**Comment by jules32** [comment]
Hi @stefaniebutland et al, 

This looks great! Here is some feedback:

- I like the preview and ending, thanks for adding it!
- Yes, please add links/definitions of linters and refactoring. Actually, the first time I heard of refactoring was from the pre-community-call discussion! 
- Could you please use this link for Melanie (@Melsteroni): http://ohi-science.org/news/people-of-ohi-melanie-frazier

Thank you!

**Comment by ha0ye** [comment]
💯 Looks awesome!

I agree that some of the terms could be defined, or links added. Maybe include a link for unit testing, continuous integration, and container as well?

Line 52 has a typo - "knowldege"

**Comment by Melsteroni** [comment]
I really like the organization of the post.  Thanks for the excellent summary.

**Comment by stefaniebutland** [comment]
Thank you for your comments @jules32 & @ha0ye.

- Updated post with links for linters and refactoring suggested by Carl in forum: https://discuss.ropensci.org/t/how-do-you-review-code-that-accompanies-a-research-project-or-paper-help-ropensci-plan-a-community-call/1321/48
- fixed Line 52 has a typo - "knowldege"
- added link to video etc in preface


> Could you please use this link for Melanie (@Melsteroni): http://ohi-science.org/news/people-of-ohi-melanie-frazier

That's the link I used from @Melsteroni's name in authors list. Let me know if I misunderstood your comment @jules32 . https://deploy-preview-345--ropensci.netlify.com/blog/2018/11/29/codereview/

> first time I heard of refactoring was from the pre-community-call discussion!

I'm relieved. Classic feeling: I thought it was just me

**Comment by stefaniebutland** [comment]
> Maybe include a link for unit testing, continuous integration, and container as well?

I'll get links for these. Open to suggestions (out of my depth but I know how to find out 🙂)

**Comment by maelle** [comment]
Maybe https://juliasilge.com/blog/beginners-guide-to-travis/ and chapters from Hadley Wickham's R Packages book? Not sure reg containers.

**Comment by noamross** [comment]
Possible links for containers:
-  Carl's paper on the topic: https://arxiv.org/pdf/1410.0846.pdf
-  My list of resources: https://github.com/noamross/nyhackr-docker-talk#links-to-topics-and-resources-dicussed-in-the-talk-and-more

**Pull request merged**
