### PR TITLE
Blog post for qualtRics relaunch

### PR DESCRIPTION
**Pull request by juliasilge**
Here is my blog post about taking over as maintainer for qualtRics @stefaniebutland! Let me know if you'd like to see any changes.

### CODE REVIEW

**Comment by stefaniebutland** [comment]
Thank you @juliasilge. I will have a look Monday morning

**Comment by stefaniebutland** [comment]
@juliasilge this post is a pleasure to read and it feels like there's something for everyone, while still being concise. I particularly appreciated that you linked to external resources in lots of the "right" places. Thank you for taking the time to do this. April 30 publication is 👍

I'm sorry about the known headings formatting issue where `####` text wrap looks really bad. With `###` the headings look big but the text wraps nicely so you might want to use that.

I have minor suggestions
- in "package’s previous authors", could you say "package’s original authors"? Saying "previous" sounds like their contributions are gone, and I imagine that's not your intent. 
- A lot of people crave CRAN insights. There are two places I'm wondering if you might link to external info if it exists.
  - In this paragraph, "After the bulk of my analysis work was done for the survey, ..."  is there one link to helpful CRAN info that readers seek?
  - The phrase "... using testthat for tests but not having it included in Suggests" is opaque to me (100% novice). Any way to add info or link to something explanatory that might ease the anxiety of a first time CRAN submitter?
  - not sure if this is helpful https://ropensci.github.io/dev_guide/building.html#crangotchas
- please put pkg names in backticks `qualtRics` as you have done for function names. 


Aside: We have begun to encourage people to add their use cases of rOpenSci packages to our public forum and we tweet about them from rOpenSci once a week. Would you mind adding your use of `qualtRics` at SO to https://discuss.ropensci.org/c/usecases? Great example of industry use. Appreciate any feedback on the template we provide - it's only been used by a few people so far.

Thank you again Julia. Really looking forward to tweeting about this on Apr30!

**Comment by juliasilge** [comment]
Thank you so much for this review @stefaniebutland!

I changed a bit of wording around previous/original authors. One thing to note here, though, is that this package did have even **earlier** authors that the previous authors to me inherited it from, so it would not be correct to refer to the maintainer before me as the original maintainer. This package has gotten passed around!

Other than that, I added a few more links with resources for CRAN policies and guidelines.

I will put together a use case for the Developer Survey over the next few days. 👍

**Comment by stefaniebutland** [comment]
Those updates address my comments perfectly. I'll tag you in the rOpenSci tweet about this post on Apr 30. 

Thank you @juliasilge! and thanks in advance for submitting a use case.

**Pull request merged**
