### PR TITLE
(don't merge yet) Create security Comm Call

### PR DESCRIPTION
**Pull request by stefaniebutland**
Only merge after timezone issue https://github.com/ropensci/roweb2/issues/427 is fixed

### CODE REVIEW

**Comment by maelle** [comment]
Occasion for me to look again at how things look like when there are several next calls. :grin: Doesn't it look a bit busy? Should there be a bigger vertical space between the two calls?

**Comment by stefaniebutland** [comment]
Yes please @maelle. That struck me when I did the PR

**Comment by maelle** [comment]
Could I push to this branch or are you going to merge today (in which case easier for me to see edits w/o creating fake comm calls locally)? I'd do it tomorrow.

**Comment by maelle** [comment]
Besides,  any further idea on top of wider vertical space is of course welcome!

**Comment by stefaniebutland** [comment]
Not urgent for me to merge so you can push to this branch if best for you

**Comment by stefaniebutland** [comment]
> any further idea on top of wider vertical space is of course welcome!

My comments - acknowledging not all are fixable (easily)
- yes more vertical space above title of 2nd Call
- the fonts of "Next Calls" and title and date/timezone conflict with readability
- too much space between speaker names?
- "Promotion blog post" is hidden but it's the key to detailed information. In addition to a formatting fix, can we call it something like "Announcement blog post"?

**Comment by maelle** [comment]
Thanks for letting me push to this branch, it is easier for me indeed.

>  yes more vertical space above title of 2nd Call

Enough now? Note that it is the space after each call so it's also below the second call.

> the fonts of "Next Calls" and title and date/timezone conflict with readability

I do not understand, should one of them be smaller/not bold?

> "Promotion blog post" is hidden but it's the key to detailed information. In addition to a formatting fix, can we call it something like "Announcement blog post"?

How do you like the new formatting?

**Comment by stefaniebutland** [comment]
Formatting for "Announcement blog post" is perfect!

> Enough now? 

A little more space would be even better I think

> the fonts of "Next Calls" and title and date/timezone conflict with readability

>Next Calls
>Research Applications of rOpenSci Taxonomy and Biodiversity Tools
> 🕓 Wednesday, March 27, 2019, 2PM PST. Find your timezone.

I am lame at design so don't have concrete solution to propose. Will try to express what I see in https://deploy-preview-428--ropensci.netlify.com/commcalls/

- maybe more space between Next Calls, Title, and Date would help
- more space between Announcement blog post and Topic and Join the call? It looks generally crowded
- put date in regular text font?
  - having ~ 5 different fonts between Next Calls and Join via Zoom makes it look busy/ messy
- date looks right and left justified for March 27 call, in this preview, but not live site and not for May 7 call

**Comment by maelle** [comment]
> I am lame at design

well so am I :joy: I've made a few tweaks based on your suggestions. I can update again tomorrow morning based on the comments you'll have made until then. :smile_cat:

**Comment by stefaniebutland** [comment]
Nice improvement!

Can "Topic" text be left-justified only, not left and right?

I'm wondering if left-justified Title might make it look even cleaner. Its current font should still distinguish it from the details below it. You can make that decision and merge I think

**Comment by maelle** [comment]
I won't merge because I'm not sure I put the text "below drop-down" in the right place, did you actually want to include it in the comm call file? It's now in the layout file so appears at the very end.

**Pull request merged**
