### PR TITLE
auk blog post

### PR DESCRIPTION
**Pull request by mstrimas**

### CODE REVIEW

**Comment by stefaniebutland** [comment]
Thank you @mstrimas! Post looks good and I love the hex. Nothing further needed from your end as far as I can tell. Publishing & tweeting on Aug 7th

**Comment by maelle** [comment]
@mstrimas I don't see the logo at all in the preview?

I was just wondering if you could add _one sentence_ about the origin of the name `auk`? Closest bird name to awk?

**Comment by mstrimas** [comment]
@maelle that's strange, I see the logo right below the date. Although I'd rather it be inline with the text or center aligned rather than left aligned. I tried fiddling with the `align` attribute, but it doesn't do anything. Do you or @stefaniebutland know how to do that?

I'll add some text about the origin of the name, I forget not everyone is familiar with both birds and unix command line tools.

**Comment by maelle** [comment]
@mstrimas as you'll have seen in `auk` repo I started preparing data for my own post on Windows and got a bug with the CRAN version. In the installation part of your post could you recommend Windows users to install v0.2.3 from GitHub unless you plan a CRAN submission before your post is up?

We can then update the post once the CRAN version is >0.2.3.

A small thing, could you add a clickable link to the GitHub repo when writing "from GitHub"?

**Comment by mstrimas** [comment]
Interesting, the CRAN version (0.2.2) was intended to fix a bug on Windows, but the GitHub version doesn't have any intended bug fixes. Obviously I must have inadvertently fixed something... Testing has been a pain because I don't have easy access to a Windows computer, so I really appreciate any feedback and bug reports from someone using auk on Windows!

**Comment by maelle** [comment]
Oh I had a CRAN version from 2 weeks ago sorry! I can try again with the brand new one. Was the bug in auk_clean?

**Comment by mstrimas** [comment]
Ok, that makes sense, I released 0.2.2 on CRAN about a week ago. The fix was for auk_clean and auk_filter, it was an issue with a `system2()` call not working.

**Comment by mstrimas** [comment]
The new changes I've added in the upcoming 0.2.3 are to accept an `EBD_PATH` environment variable that can be set to the directory where the data are stored. It's not feasible to put the data in a project directory because of the size, so they need to be stored in a central location to be accessed by all projects. The intention of `EBD_PATH` is to avoid having to use absolute paths to that central directory to increase code portability. There's an `auk_set_ebd_path()` function to help set the environment variable. Curious what you think about this solution.

**Pull request merged**
