### PR TITLE
Add post about new code of conduct

### PR DESCRIPTION
**Pull request by stefaniebutland**

### CODE REVIEW

**Comment by stefaniebutland** [comment]
@sckott @karawoo I made only ~formatting edits to the draft blog post. Decided to publish the post Mon Jan 14 to announce at start of a week instead of Friday and to not take attention away from this week's ozunconf posts.

I can change to publish Fri Jan 11 if you prefer

**Comment by stefaniebutland** [comment]
I think I won't mention versioning in the post. We didn't make rules about versioning, but perhaps I'll ask about that when we make our first change 😜

**Comment by sckott** [comment]
let's do remember to have the discussion about what constitutes a bump in the version, maybe there's best practice in other code of conduct's we can follow

**Comment by karawoo** [comment]
Looks good to me

**Pull request merged**
