### PR TITLE
make form easier to see?

### PR DESCRIPTION
**Pull request by maelle**
cf #297 
I have trouble reading the text https://ropensci.org/contact/ the contrast is very low

### CODE REVIEW

**Comment by maelle** [comment]
I found where to change the color for the form border, but not for its content which I thought was --placeholder... 🤔 

In any case @karthik I am bad at choosing colors. I just think the current forms are very light (or is my screen too luminous?!)

**Comment by maelle** [comment]
Cf bottom of https://deploy-preview-312--ropensci.netlify.com/community/ (subscription)

And https://deploy-preview-312--ropensci.netlify.com/contact/

**Comment by maelle** [comment]
Edited to add: even when using Chrome developer tools, I can't change the color of the placeholder text! 😕

**Comment by karthik** [comment]
Hi @maelle,
I've added a couple of commits to increase contrast. This is what it looks like:

image


to change this color, you have to edit `general.pcss` and update `   --form_border: #5a6376;`.
Then you need to run:

```
cd themes/ropensci/static/
npm install . --no-optional
npm run css
```
to generated the updated css for the whole repo.

**Comment by karthik** [comment]
Sorry, I see that you figured out border color. Your color choice is fine, just something with more contrast.

To change the placeholder text color: you need to change this in `general.pcss` `    --placeholder: #090a0c;`

**Comment by maelle** [comment]
IIRC I tried and it didnt work, even unchecking the color in Chrome developer tools didn't work, but I can try again. 🤔

**Comment by maelle** [comment]
@karthik in the files of this PR you can see the text color was changed without any consequence 😢

**Pull request merged**
