### PR TITLE
add links to both GitHub organizations from footer

### PR DESCRIPTION
**Pull request by maelle**

### CODE REVIEW

**Comment by maelle** [comment]
The footer is really getting crowded :crying_cat_face:

**Comment by stefaniebutland** [comment]
can you remove the comma after `ropensci` & GH icon?

**Comment by maelle** [comment]
@sckott, any feedback?

**Comment by sckott** [comment]
@maelle i think it looks good. but I don't have a designers eye

**Comment by jeroen** [comment]
I think this is too crowded, indeed. Here is an alternative, to add the ropenscilabs link as an icon: https://github.com/ropensci/roweb2/pull/387

**Comment by maelle** [comment]
:tada: Thank you!!

**Pull request closed without merging**
