### PR TITLE
footer

### PR DESCRIPTION
**Pull request by maelle**

### CODE REVIEW

**Comment by karthik** [comment]
image

Would the white one look more in line with the existing color scheme?

**Comment by maelle** [comment]
Trying it now.

I wasn't able to align the svg to the left when I tried this morning 😭 I suppose I should try again unless centered is ok?

**Comment by karthik** [comment]
I'm not a css expert and cannot get it to align left on every device. Best I can do for desktop is:

```css
<img src="https://www.netlify.com/img/global/badges/netlify-light.svg" alt="Deploys by Netlify" height="14%" style="margin:0px 0px 0px -100px">

Will have to ask the designer to fix this. But for the time being I don't mind the thing being off center.
```

**Comment by maelle** [comment]
In that case I guess you can merge this. 👍

Depending on the new layout, maybe no fix will be needed, and in any case it'll make more sense to dive into divs/grid/etc at that point rather than now with the current layout.

**Pull request merged**
