### PR TITLE
draft post on unconf tips

### PR DESCRIPTION
**Pull request by stefaniebutland**
cross-posting with permission from https://blog.trelliscience.com/six-tips-for-running-a-successful-unconference/

### CODE REVIEW

**Comment by stefaniebutland** [comment]
Can someone advise me on how to fix couple of formatting issues?
- long headings that wrap onto next line look squashed
- In YAML `preface` if I add hyperlink, `hugo serve` gives error. Want to add link(s) here to point to source of cross-posted blogs

**Comment by sckott** [comment]
will take a look @stefaniebutland

**Comment by sckott** [comment]
first i think has to do with spacing between lines - not sure exactly which styling thing needs to be tweaked for that

second thing: did we do this before and it worked?

**Comment by stefaniebutland** [comment]
> second thing: did we do this before and it worked?

No, not done before.
@jeroen added `preface` to YAML so we didn't have to use html `alert` (or something) to do this as we did on old site e.g. https://ropensci.org/blog/2017/07/18/value-of-welcome/

**Comment by sckott** [comment]
hmm, not sure how to do that then

**Pull request merged**
