### PR TITLE
Vertical Alignment for paragraph wasn't defined so bullet went to the…

### LINKED ISSUE #172: bullet CSS
Something is odd with display of list items on the blog.  The bullets show up at the _last_ line of a list item (example below).  As far as I can tell, this has something to do with the fact that list items are wrapped in `<li><p>Text</p></li>` rather than just  `<li>Text</li>`.  Not sure if that means the CSS should change, or the way the markdown compiles should change, or something else.

screenshot 2018-04-11 10 45 44

(from https://ropensci.org/blog/2018/03/16/thanking-reviewers-in-metadata/)

### PR DESCRIPTION
**Pull request by marulango**
… bottom of the list item Fixes #172

### CODE REVIEW

**Comment by maelle** [comment]
Lists look good now 😺 

I see less margin before paragraphs cf https://deploy-preview-265--ropensci.netlify.com/blog/2018/08/21/birds-radolfzell/ vs https://ropensci.org/blog/2018/08/21/birds-radolfzell/

**Comment by karthik** [comment]
I agree with Maëlle

image

**Comment by marulango** [comment]
screen shot 2018-08-29 at 10 13 44 am
screen shot 2018-08-29 at 10 15 37 am

Fixed the spacing :D

**Comment by karthik** [comment]
great, thanks!

**Pull request merged**
