### PR TITLE
add author names in tech notes list 

### PR DESCRIPTION
**Pull request by maelle**
cf #229

### CODE REVIEW

**Comment by maelle** [comment]
Preview: https://deploy-preview-309--ropensci.netlify.com/technotes/

@stefaniebutland adding author names to that page was your suggestion.
@jeroen I'm sure you'll have good ideas.

Please also look at lines where tech notes have several authors, I've separated them with "|" at the moment.

**Comment by jeroen** [comment]
I think it's a bit crowded. Could you try how it looks if you wrap the author name in `<small>` or `<i>` tags.

**Comment by maelle** [comment]
Here's italic. I thought small looked too small, but I can change the i tag to that if you prefer.

**Comment by maelle** [comment]
Deal!

**Comment by maelle** [comment]
Ok, thanks! I'll copy that over to the archive partial from #313

**Pull request merged**
