### PR TITLE
Authors partial

### PR DESCRIPTION
**Pull request by maelle**
cf #324

### CODE REVIEW

**Comment by maelle** [comment]
@stefaniebutland this PR removes duplication of code creating authors lists because this code will be re-used yet again in calendar and comm calls stuff if all goes well, and because it's generally better to not repeat oneself. 😺 

In one of the authors list generating code (in the technotes single template cc @jeroen), there was something generating a Twitter icon, which I've kept since it must have been a decision at some point. See how it looks for your post where I added your Twitter username (I can remove it, it's for testing that part of the partial!). I had no idea that there was any interesting in storing name+url _+twitter_ for authors!

* blog page https://deploy-preview-325--ropensci.netlify.com/blog/

* single post https://deploy-preview-325--ropensci.netlify.com/blog/2018/10/24/commcall-nov2018/

* tech note https://deploy-preview-325--ropensci.netlify.com/technotes/2018/10/16/pubchunks/

**Comment by maelle** [comment]
The more I see the Twitter icon, the more I like its presence, it can only help with interactions, and it's quite minimalist.

**Comment by maelle** [comment]
We could easily add the Twitter username of all staff&leadership members automatically to old posts, I can do that if you agree @stefaniebutland

**Comment by stefaniebutland** [comment]
> We could easily add the Twitter username of all staff&leadership members automatically to old posts, 

Seems like a good idea to me

**Comment by maelle** [comment]
Thanks! Will merge this, I'll add Twitter info for all old posts by staff &leadership in a further PR.

**Pull request merged**
