### PR TITLE
update tags using blogyaml tool

### PR DESCRIPTION
**Pull request by stefaniebutland**
updated blog and commcall tags using `blogyaml` tool from @maelle. 

Concerned about an apparent change in format of `authors` without me intentionally touching them

### CODE REVIEW

**Comment by stefaniebutland** [comment]
checks have failed. @maelle when you have time, appreciate you having a look at this and let me know if I've made an error

**Comment by maelle** [comment]
No, I made one! I'll fix that :smile_cat:

**Comment by maelle** [comment]
It now looks good to me.

**Comment by maelle** [comment]
(and `blogyaml` latest version no longer breaks the authors field :-) )

**Pull request merged**
