### PR TITLE
Upgrade Hugo

### PR DESCRIPTION
**Pull request by maelle**

### CODE REVIEW

**Comment by maelle** [comment]
When the preview is rendered @stefaniebutland please have a look around to see if anything looks weird.

**Comment by maelle** [comment]
Noting for myself that the reason for the change we observed is probably
https://github.com/gohugoio/hugo/commit/1cbb501be8aa83b08865fbb6ad5aee254946712f in https://gohugo.io/news/0.56.0-relnotes/ (I'm not going to test all Hugo versions hehe)

**Comment by maelle** [comment]
I see a discourse error.

**Comment by maelle** [comment]
But maybe the error is expected, do we expect the comment field to not exist in previews?

**Comment by stefaniebutland** [comment]
> the error is expected, do we expect the comment field to not exist in previews?

Comment field does not exist in previews

**Pull request merged**
