### PR TITLE
add pkgs.json

### PR DESCRIPTION
**Pull request by mpadge**

### CODE REVIEW

**Comment by stefaniebutland** [comment]
guessing @maelle might be best to review this

**Comment by maelle** [comment]
Thanks @mpadge! Can you knit with `rmarkdown::render`? For some reason (different output format in a knitting function?) index.md doesn't have YAML metadata.

**Comment by mpadge** [comment]
@maelle The `index.md` has been `render`ed, but that does not include the YAML metadata, nor do i know how to get that to appear. Sorry

**Comment by maelle** [comment]
no problem, but out of curiosity, how did you render it? I'm imagining other folks authoring posts on our website might get the problem.

**Comment by mpadge** [comment]
> no problem, but out of curiosity, how did you render it? 

Plain base R, no RStudio, no sneaky envvars, and just `rmarkdown::render(..., output_file = "index.md")`.

**Comment by maelle** [comment]
ah maybe it'd work without `output_file` :thinking:

**Comment by mpadge** [comment]
Oh dear, no, sorry, actually i was defaulting to
``` r
rmarkdown::render('$(LFILE).Rmd',rmarkdown::md_document(variant='gfm'))
```
where the 2nd arg is `output_format`, and of course `gfm` strips all YAML data. Do you want me to update?

**Comment by maelle** [comment]
no, no worries, I did it myself! 

I'm glad to know you used `output_format`, now this is all less mysterious :grin:

**Pull request merged**
