### PR TITLE
fancier author pages

### PR DESCRIPTION
**Pull request by maelle**
Notes
- still quite ugly, no doubt about that, hence my asking for your feedback @jeroen. I think At the moment it looks ok for authors with many posts, less so for authors with only one or two posts.
- I defined a new section called author in sections.pcss to deal with image and icon styling/sizing.
- I now use bootstrap because that's what Hugo academic theme does and I used that as inspiration once I realized the two-columns layout looked like :hankey: on my tablet.
- I created an archiveauthors.html partial that's like archive.html (your tech note list design, basically) except the date format is 2006/01/02 because otherwise the date was always on two lines.
- I'm annoyed at our having stored team pictures at 133x133 pixels. In the team page, the size is fixed by the image, not by html/css. I'd prefer our storing them in a bigger format, so we could have a bigger image for the author index pages.

### CODE REVIEW

**Comment by maelle** [comment]
* Stef https://deploy-preview-402--ropensci.netlify.com/authors/stefanie-butland/ (has an img field in metadata, only one at the moment)
* Me, default avatar https://deploy-preview-402--ropensci.netlify.com/authors/maelle-salmon/
* Kara, GitHub avatar https://deploy-preview-402--ropensci.netlify.com/authors/kara-woo/

**Comment by maelle** [comment]
cf #381

**Comment by maelle** [comment]
The pics look too big on mobile.

**Comment by maelle** [comment]
By the way the website header doesn't look really well in a reduced window, the section names are very close to each other.

**Comment by maelle** [comment]
Thanks!

> I like the general structure of the page

Great!

> sizes of menu bar on the author page are off

Oh yes indeed. I think it might be due to the bootstrap script I added to get the responsive behavior. How else could I add such a behavior? Cf current solution in https://github.com/ropensci/roweb2/pull/402/files#diff-bb15ed0b4ec90364eea64fdfb3d81ce1

>   can we do better default pictures based on people's github or twitter picture?

What do you mean? :-) I added as many GitHub accounts as I could find automatically from the existing metadata, and that's what's used in the absence of an `img` field (only need to add GitHub accounts for staff). Twitter images are not as easy to get so I wouldn't try that. The issue is adding GitHub usernames and we could do that in the future, by hand.

>  please properly indent the added lines to sections.pcss

Will do at the same time as working on removing bootstrap when we find another solution. :angel:

**Comment by jeroen** [comment]
You really should not add extra (bootstrap) scripts. We have our own style files that deal with the responsiveness. The bootstrap styles will override and conflict that those.

**Comment by maelle** [comment]
I understand that, hence my asking how to add the screen condition. Any example in the existing templates?

**Comment by maelle** [comment]
I'll try that then, fingers crossed.

**Comment by maelle** [comment]
@jeroen hmm actually now it magically looks good?! No idea why I had needed to add bootstrap earlier. Are you fine with the current look? I also fixed the indentation of section.pcss (I think!).

For staff and other authors of more than 3 posts I've added the GitHub username by hand when it was missing. I've also added your and my GitLab usernames to see how the GitLab icon looks like, see https://deploy-preview-402--ropensci.netlify.com/authors/jeroen-ooms/

@jeroen @stefaniebutland @sckott As long as we do not store the team pictures in a bigger format and correspondingly edit the template for the team section, I'm in favour of using GitHub pictures for staff and leadership author pages because 133x133 pics are too small. I won't have time to change the team pics and section in the short term but I plan to, at the same time as the collaborators section. If you're not happy with this maybe someone else than me can
* ask folks to upload/send a higher resolution portrait,
* add width="133" in the about.html partial.
_I_ think GitHub pics are fine, but @sckott's one isn't very informative :wink:

@stefaniebutland note that bio for editors are added via #412

**Comment by maelle** [comment]
@stefaniebutland with this new page template, the guidance for authors will need to be updated. Maybe with link to rendered author pages to show the icons?

```
---
name: Kelly O'Briant
link: https://kellobri.github.io/
twitter: kellrstats
gitlab: yourgitlabusername
---
```
"Please provide your name and at least a link/username. The `link` field is meant for your preferred online presence URL, to be filled only if you have one that's not your GitHub, GitLab or Twitter account. The `twitter`, `github` and `gitlab` fields are for your Twitter/GitHub/GitLab usernames (without "@")."

In theory if there were a big demand for another icon we could add it, e.g. for LinkedIn. We could even do that with academicons but it'd require a bit more work, hopefully it'd be as easy as fontawesome icons.

**Comment by jeroen** [comment]
It looks so much better now. One small thing: when I click on a name on the top of a blog post, it has a link hardcoded to `www.ropensci.org` so it leaves the preview sites. We should use a relative link there that does not hardcode the domain.

**Comment by maelle** [comment]
Thanks @jeroen!

> when I click on a name on the top of a blog post, it has a link hardcoded to www.ropensci.org so it leaves the preview page. We should use a relative link there that does not hardcode the domain.

Good catch, replaced `.Permalink` with `.URL` in the authors.html partial.

 > The name title on the author page is very large it can be a bit smaller.

Now h3 instead of h2, good to go?

 > the code in archiveauthors.html has one too many closing </div> within the <section>?

Indeed! I fixed the archiveauthors.html partial on this branch and the archive.html template on master.

 > the line spacing between the post titles on the author page is a bit much. Would be nicer to match the same line spacing from e.g. the technotes list.

I am very puzzled by this. It's nearly the same partial that's used in the technotes list, archive and tag pages (archiveauthors.html is the same as archive.html except from the date format). :thinking: I guess it's because in the case of the author page the partial is called from within `<div class="col-8 top-4">`. I am honestly not sure how to fix this. I tried changing the div, and tried finding what the parameter is with the web inspector, but it does not seem to be line-height. Any help welcome.

**Comment by jeroen** [comment]
Thanks! I think this is good for now, I may try to tweak the style a bit more later.

**Comment by maelle** [comment]
Wow that was fast, thank you! Of course feel free to tweak the style :art:

**Pull request merged**
