### PR TITLE
correct the lingtypology blog post

### PR DESCRIPTION
**Pull request by agricolamz**
Dear @sckott, dear @stefaniebutland,

sorry that it took me so long, I've been away for a week.

### CODE REVIEW

**Comment by agricolamz** [comment]
Hm... It should be [here](https://deploy-preview-141--ropensci.netlify.com/blog/2017/05/16/easy-linguistic-mapping-with-lingtypology/)? But it is not...

**Comment by sckott** [comment]
@agricolamz is this not it https://deploy-preview-141--ropensci.netlify.com/blog/2017/05/16/lingtypology/ ?

**Comment by agricolamz** [comment]
@sckott, yes... Aha, I've used the link from the old deploy, so it haven't changed the link to new one!

**Comment by agricolamz** [comment]
@sckott, may I make another small change. There is not a word about how long lines are possible for the blog post, so it is too long in one chunk.

**Comment by sckott** [comment]
thanks for the fixes @agricolamz !!! merging now

**Pull request merged**
