### PR TITLE
change color of comments

### LINKED ISSUE #246: Code highlighting
I find the color of comments in R code chunks quite dark, I'm starting to wonder whether it's readable by all (some people have trouble seeing stuff with low contrast so maybe this is an issue?). 🤔

### PR DESCRIPTION
**Pull request by maelle**
Fix #246 

Or would some sort of grey be better?

cf e.g. https://deploy-preview-669--ropensci.netlify.com/technotes/2020/03/19/parzer/

### CODE REVIEW

**Comment by sckott** [comment]
a grey would be better I think, do you agree @jeroen ?

**Comment by jeroen** [comment]
Yes, it is difficult to distinguish from regular code now.

**Comment by maelle** [comment]
With https://webaim.org/resources/contrastchecker/ and the current background colour, the darkest grey that passes all tests is honestly not much different from code (see further down).

At the moment the combination background-comment color fails all contrast tests, so I think we can agree it's really bad.

Of course there's a compromise: making comments different from code vs making comments different from background.

Current code color

image

A comment color that's a bit different but fails WCAG AAA (Passses WCAG AA) `#96A2AB` (The yellow comments in this PR are actually more different from code?)

image

I'd prefer the colour combination background-comment to pass all contrast checks (i.e. both "AAA" and "AA" for "normal text"). 

Do you have any colour suggestion @sckott @jeroen?

**Comment by sckott** [comment]
At least in the case of the output of code, one can just never use `collapse=TRUE`, so output is in a different code block. But that doesn't solve the problem for comments within code blocks. 

I don't have any ideas for a color or colour

**Comment by maelle** [comment]
> At least in the case of the output of code, one can just never use collapse=TRUE, so output is in a different code block. But that doesn't solve the problem for comments within code blocks.

What do you mean?

@jeroen? :slightly_smiling_face:

**Comment by sckott** [comment]
there's the knit option `collapse`. if `collapse=FALSE`, then the output is in a separate block of code, making it easier to distinguish from the code itself.

**Comment by jeroen** [comment]
I think this comment color is way too bright, it makes it very difficult to read the code. This almost defeats the purpose of syntax highlighting. Maybe we should wait for an expert on this.

**Comment by maelle** [comment]
The problem is that it means the comments are unreadable for some at the moment.

**Comment by jeroen** [comment]
Yes I understand that but with this solution they are unreadable for everyone :)

**Comment by maelle** [comment]
further related things in #681 #666

**Pull request closed without merging**
