### PR TITLE
Extracting eBird Data from a Polygon

### PR DESCRIPTION
**Pull request by maelle**
[Original post](https://strimas.com/post/extracting-ebird-data-polygon/)

[Source](https://github.com/mstrimas/strimasdotcom/tree/master/content/post/2020-04-02-extracting-ebird-data-polygon)

### CODE REVIEW

**Comment by maelle** [comment]
@mstrimas Thanks again for agreeing to repost your post! :pray:

[Preview](https://deploy-preview-652--ropensci.netlify.com/technotes/2020/04/16/ebird-polygon/)

* I added an intro with a link to your post.

* I saw that auk was updated on CRAN so I updated the installation instructions.

* At the end of the post could we add something about how to interact with you in case the readers e.g. want to contribute to auk? (some sort of call to action)

**Comment by mstrimas** [comment]
Looks great, thanks for putting this together! Folks are welcome to submit issues on GitHub with bug reports or feature requests, or to email me directly. There is also a vignette specifically for adding functionality to the package: https://cornelllabofornithology.github.io/auk/articles/development.html

**Comment by maelle** [comment]
Thank you! I added a conclusion based on your two sentences.

I linked to the vignette on auk website rendered by [rOpenSci docs server](https://ropensci.org/technotes/2019/06/07/ropensci-docs/), I hope it's fine? (same question for the link in the post intro)

**Comment by maelle** [comment]
I am quite impressed that you have an article about auk development by the way, that's really cool!

**Comment by stefaniebutland** [comment]
@maelle should this line be in YAML `preface`? "This tech note about the peer-reviewed auk package was first posted on Matthew Strimas-Mackey’s website and kindly contributed to this blog."

**Comment by mstrimas** [comment]
@maelle everything looks good to me!

**Comment by maelle** [comment]
@mstrimas great, thanks again!

@stefaniebutland thank you! I made the intro a preface and the link in the preface already was a link to the original post, à la R-Bloggers. So we're done?

**Comment by stefaniebutland** [comment]
@maelle I meant [his 2018 post](https://ropensci.org/blog/2018/08/07/auk/). Sorry if I missed it in the post

**Comment by maelle** [comment]
Oh now I see, sorry. I've made a commit adding a link to the 2018 post in the preface, and now both posts have the "auk" and "ornithology" tags.

**Pull request merged**
