### PR TITLE
blog post 2months in 2mins august

### PR DESCRIPTION
**Pull request by stefaniebutland**

### CODE REVIEW

**Comment by stefaniebutland** [comment]
@sckott fyi I cheated / got carried away in Use Cases section and highlighted an example not in a newsletter. I'll change the example to this one [you highlighted](https://news.ropensci.org/2019-08-05/) and we can use my example in a future newsletter or other.

Screen Shot 2019-08-13 at 8 20 50 PM

**Comment by stefaniebutland** [comment]
@karthik  @sckott Appreciate your feedback on this 2nd newsletter summary post so I can settle on a template for future use. Publishing Thurs Aug 15

preview: https://deploy-preview-507--ropensci.netlify.com/blog/2019/08/15/news-aug2019/

**Comment by karthik** [comment]
The emojis are overwhelming in an unpleasant way. And overall the formatting looks really busy (not your fault. It's our awful web design).

**Comment by stefaniebutland** [comment]
Thanks for the comments

Changes in new version:
- I took out emojis
- got rid of bullets in software peer review
- in software peer review sections, package names in boldface (but not elsewhere)
- added spacing before section headings
- changed use case example to that in newsletter 

If @karthik has no further suggestions for improvement I'll publish this tomorrow:
https://deploy-preview-507--ropensci.netlify.com/blog/2019/08/15/news-aug2019/

**Comment by karthik** [comment]
This version looks so much cleaner. 💯
🛳️

**Pull request merged**
