### PR TITLE
Twitter cards 

### PR DESCRIPTION
**Pull request by maelle**
cf #290

### CODE REVIEW

**Comment by maelle** [comment]
https://cards-dev.twitter.com/validator

**Comment by maelle** [comment]
Right now there's no `description` field in any post/note YAML. I could add them via `blogdown` internal functions (like for tags) and fill it with the first paragraph, or I could try and tweak the card code to use the first paragraph in the absence of the field (probably better).

**Comment by maelle** [comment]
it looks ok for posts now 

image


although I need to use a shorter logo.

**Comment by maelle** [comment]
What doesn't work at the moment is the card for e.g. https://deploy-preview-291--ropensci.netlify.com/community/ and https://deploy-preview-291--ropensci.netlify.com/

**Comment by maelle** [comment]
I see why it doesn't work for anything that's ropensci.org/SOMETHING (I need to change the conditions, otherwise for such pages the card template is the one for tutorials/blog posts etc) but not sure yet why it doesn't work for the home page itself.

**Comment by maelle** [comment]
Note that I need to check whether having the same head for all single.html is ok (this adds GA partial to tutorials and usecases)

**Comment by maelle** [comment]
example with `twitterImg` parameter 
image

**Comment by maelle** [comment]
Issues at the moment:
* A better logo should be chosen as default image.
* I now use the same head partial everywhere which is bad because the home one has jquery (now all do), the tutorials one had the page title (and now it's lost) etc. so I'd need to consolidate this somehow... not sure how.
* Twitter cards not working for anything with a depth of 0 or 1 from the home URL but I think I'm solving it with my reckless use of the head partial everywhere.

**Comment by jeroen** [comment]
Looks good to me, thanks!

**Comment by maelle** [comment]
@jeroen thanks your help!

**Pull request merged**
