### PR TITLE
sort packages by latest commit

### PR DESCRIPTION
**Pull request by maelle**

### CODE REVIEW

**Comment by maelle** [comment]
An alternative is using https://datatables.net/reference/option/initComplete

**Comment by jeroen** [comment]
Yes it's better to set a default sorting in the view (i.e data table) not shuffle data itself.

**Comment by maelle** [comment]
I made a new proposal :-)

**Comment by jeroen** [comment]
Thanks! 

This also reveals that some of the repo's that are marked as 'inactive' in the registry are actually very active 🤔

**Pull request merged**
