### PR TITLE
Registry edits

### PR DESCRIPTION
**Pull request by maelle**
Following work in #292

### CODE REVIEW

**Comment by maelle** [comment]
CRAN filter repaired 😌

**Comment by maelle** [comment]
The JSON is in https://github.com/ropensci/roregistry/blob/ex/registry2.json

**Comment by maelle** [comment]
The active filter seems to actually completely mimick the CRAN filter 🤔

**Comment by maelle** [comment]
* the GitHub and comments icons are now font-awesome.

* but the comments icon is on its own line.

* active filter still broken.

**Comment by maelle** [comment]
I really don't know how to fix the icon issue, I've just tried adding a display "inline" CSS property for the `fa` class, without success.

**Comment by maelle** [comment]
@jeroen Things I'd need help with 🙏 

* How to display all icons on a single line

* Whether part of the icon stuff that's in the JSON now should go to a css file (e.g. https://github.com/ropensci/roregistry/blob/a7b4ca957c79a3cd9af5367932a2df97ceb9519a/registry2.json#L93 )

**Comment by jeroen** [comment]
I think the `<div class="container">` is missing again...

**Comment by maelle** [comment]
Thanks, it should be ok now.

So maybe we can say I can merge once the deployment of that JSON is sorted out? Or is there anything else I should fix first?

**Comment by maelle** [comment]
@sckott does https://deploy-preview-308--ropensci.netlify.com/packages/ look ok for you too (even on mobile)? Thanks!

**Comment by maelle** [comment]
Traffic lights! (ok, not subtle)

**Comment by jeroen** [comment]
> Traffic lights! (ok, not subtle)

Maybe something like this! Perhaps just a green, red or gray bullet in front of the package. It doesn't have to even say 'status' explicitly, it can just be the bullet and then the users can click on it if they are curious what it means!

**Comment by maelle** [comment]
@jeroen like this? If so, I'll clean up the css and pcss files (since I don't need to define status labels any more)

**Comment by maelle** [comment]
also note that most of the formatting happens in `makeregistry`, see the JSON https://github.com/ropensci/roregistry/blob/ex/registry2.json Not sure I should pull out stuff from there to some CSS? 🤔

**Comment by jeroen** [comment]
Yeah that's pretty ugly. I think the JSON should only contain data fields, perhaps some markdown for markup, but not entire html snippets :/

**Comment by maelle** [comment]
Ok, first we need to agree on the status thing, then I can make the JSON cleaner.

* I'll probably create an onboarding badge class.

* And a status bullet class.

Any argument other than ugliness by the way? 😉

**Comment by jeroen** [comment]
A registry should only contain data, markup should be added by the front-end. We may want to use the registery for other clients and front-ends, that may not understand html.

If we hardcode html in the registry, this limits the usefulness of the registry to a particular front-end. It will make harder to use the data from the registry in other clients and applications.

**Comment by maelle** [comment]
* JSON now clean
* Styling in CSS stylesheets
* URL etc. creation in the JS

**Comment by jeroen** [comment]
Let's ship it! 🚢💁🚀

**Pull request merged**
