### PR TITLE
try updating font-awesome

### PR DESCRIPTION
**Pull request by maelle**
I "just" wanted to be able to use the keybase icon in author pages, and it turns out I need to update font-awesome for this.

Problems created
* the footer now looks bad
* I can't make https://fontawesome.com/icons/comments?style=solid appear in the packages table.

### CODE REVIEW

**Comment by maelle** [comment]
@jeroen for the footer it seems related to what you had done in https://github.com/ropensci/roweb2/commit/8d3a13c9658b6c68aaea79d725d9c2070e2d202f

the icons of the footer are a mix of font-awesome icon (flask) and non font-awesome icons (Twitter, GitHub, Vimeo).

**Comment by maelle** [comment]
Then, ideally, I'll also work on adding support for a few https://jpswalsh.github.io/academicons/ to authors pages (at least ORCID).

**Comment by maelle** [comment]
Author page with keybase: https://deploy-preview-481--ropensci.netlify.com/authors/ma%C3%ABlle-salmon/

Footer visible on that page.

Packages page https://deploy-preview-481--ropensci.netlify.com/packages

**Comment by jeroen** [comment]
Maybe we need to update these css entries? https://github.com/ropensci/roweb2/pull/387/files

**Comment by maelle** [comment]
Probably but I'll have to look into how. 

I'm not too sure what the former JS contained, apparently the new one also influences formatting.

**Comment by maelle** [comment]
Now I've broken icons entirely by using CSS. :female_detective:

**Comment by maelle** [comment]
@jeroen could https://github.com/ropensci/roweb2/blob/3290b9e30dcbad7d1032d937da4dbf80a33f7ef0/themes/ropensci/static/css/typesetting.pcss#L300 be the issue?

**Comment by maelle** [comment]
or probably not since it's icon with an hyphen.

**Pull request closed without merging**
