### PR TITLE
Commcalls transfer

### PR DESCRIPTION
**Pull request by maelle**
It's easier for me to first transfer comm calls, then in a second PR I'll tackle the other events.

### CODE REVIEW

**Comment by maelle** [comment]
Preview
* https://deploy-preview-334--ropensci.netlify.com/commcalls/
And click on individual call pages. https://deploy-preview-334--ropensci.netlify.com/commcalls/2016-03-02/ is weird, it has two videos, in the page sources the right URLs are used, but the embedding seems broken?

**Comment by maelle** [comment]
So for now there's no need for _now_ for the list page.
* before the call, do not fill the "date" field.
* after the call, fill it, at the same time as vimeo id adding, and the call will get added to the archive list.
Maybe not optimal, but not too bad?

**Comment by maelle** [comment]
Note to self: check how the RSS feed looks like after adding this. The comm calls will probably be in it, which might be bad.

**Comment by maelle** [comment]
Related, there might be a need for archiving collaborative notes cf https://github.com/ropensci/commcalls/issues/25

**Comment by maelle** [comment]
How information was transferred from the README of the commcalls repo to individual Markdown file: https://github.com/ropensci/commcalls/issues/24

**Comment by maelle** [comment]
Thanks a lot! deets is the field where to keep the Zoom info actually, will show an example next week.

**Comment by maelle** [comment]
Before I forget, the archive page now also includes comm calls.

**Comment by maelle** [comment]
Other note (will consolidate my comments soon): many calls don't have links to slides but I suspect some links to slides are mentioned in videos so maybe it'd be worth watching? 🕵️‍♀️

**Comment by maelle** [comment]
Thanks a ton, here are my answers. (to be updated)

# Other notes
* the archive and tags pages now include comm calls so I updated the message at the bottom accordingly. I think it's good to have comm calls in there to make them more discoverable.
* Now at the bottom of each single comm call page there's a sentence indicating where to find other comm calls. See e.g. the bottom of https://deploy-preview-334--ropensci.netlify.com/commcalls/2018-11-15/
* Many calls don't have links to slides but I suspect some links to slides are mentioned in videos/collaborative notes so maybe it'd be worth watching/looking? 🕵️‍♀️

**Comment by stefaniebutland** [comment]
I think you've gotten me to a point where it's best to dive in, merge this pull request and I figure things out as I use them. Have not commented here on all the things I love, like you adding comm calls to the archive and adding note at bottom of each comm call page that points to the others. Thank you!!

Before merging, note the formatting of preview https://deploy-preview-334--ropensci.netlify.com/commcalls/ doesn't look right in a few places - the "Join us in our quarterly Community Calls ..." text is centred, not left-justified. But the "Speakers", "Topic" section looks strange now (fully justified and has smaller margins than the listing of past calls below). (Hope I didn't create a monster by asking you to left justify, rather than centre the text)

I feel like we might need to talk this one through: The `deets` preview looks jumbled without hard returns. The yellow highlighting of deets also seems to bring too much attention to lots of text that few will use. I know it's good to have all info to join a call in one place but is there a way to have only the direct Zoom link visible along with another link that takes person to more calling options? 

> Should the files, page etc. be renamed community-calls instead of commcalls? 

No please keep as is

> We can also wait for the first time you actually create a gist for implementing this, as you prefer.

Yes let's wait to see what we really need

> Many calls don't have links to slides but I suspect some links to slides are mentioned in videos/collaborative notes so maybe it'd be worth watching/looking?

**Comment by maelle** [comment]
I changed the horizontal alignment, and added the use of a details tag for the deets, we can talk about how to make this better. 😸

**Comment by maelle** [comment]
We also need to discuss whether to link to the commcalls page directly from the website header/footer (rather than only from the community page).

**Comment by maelle** [comment]
Aaand I should not forget to clean Jeroen's last call before merging, since the dancing banana didn't actually participate in that call.

**Comment by maelle** [comment]
And before I forget, I didn't actually choose to add comm calls to the archive, that's apparently how my archives partial works, happy accident :joy: (I think I select all pages with a date, so will need to be extra cautious not to include calendar events!)

**Pull request merged**
