### PR TITLE
prepare post about the release of the dev guide

### PR DESCRIPTION
**Pull request by maelle**
@stefaniebutland is it ok if this gets published on the blog eventually? (or rather as a tech note?) what would be a good date?

We first need to actually release the new book version which would happen at the beginning of next week.

### CODE REVIEW

**Comment by karthik** [comment]
LGTM!

**Comment by stefaniebutland** [comment]
@maelle I'll suggest a date later today

**Comment by stefaniebutland** [comment]
I like this as a blog post rather than a tech note. It represents a major, central rOpenSci thing that I think we ought to give attention to.
Can publish 2019-05-16 (Thursday May 16) if that works for you.  I already have earlier dates filled on the blog.

- quaterly -> quarterly
- "all of this white on rOpenSci blue" -> "all of this in white on rOpenSci blue" because my first thought was "white" was a typo of "while"
- "features rOpenSci hex logo" -> "features the rOpenSci hex logo"
- "how hard to read the links were in the former color!" -> "how hard it was to read the links in the former color!"
- @IndrajeetPatil -> [Indrajeet Patil](https://github.com/IndrajeetPatil) to be in same format as other people cited
- "including link to examples" -> "including links to examples"
- If "After acceptance" counts as guidance, can it be added as a third item  #### under the previous heading? If not, should heading "After acceptance" parallel the former heading like "Updates to ...."?
- "direct users to rOpenSci forum" -> "direct users to the rOpenSci forum"
- "changes brought to" -> "changes incorporated into"
- "also head to the issue tracker!" doesn't quite sound right, so maybe -> "you too can head to the issue tracker!"

**Comment by maelle** [comment]
Tweet draft.

We've updated our book - rOpenSci Packages: Development, Maintenance, and Peer Review! :tada:

Highlights:

:sparkles: The book now has a cover! Work by `@LockeCreatives`

:fire: We now explicitly accept assignment with =, not only <-

:link: Read more: LINK

Image: cover, alt text from the post "cover of rOpenSci dev guide, showing a package production line with small humans discussing, examining and promoting packages"

**Comment by stefaniebutland** [comment]
will reply to main tweet with thanks to people noted in section "more legit and accessible book"

**Comment by maelle** [comment]
Great idea to thank contributors in a reply to the first tweet! We're listening even when someone suggests we use LaTeX :joy: (for the PDF export, we had to do that :crying_cat_face: )

> do you know of twitters for Katrin Leinweber or Kevin Wright?

No. @katrinleinweber I don't think you have a Twitter account?

**Comment by katrinleinweber** [comment]
I sure do, just not obviously connected to my real name. Search for tweets with "github.com/katrinleinweber" ;-> Feel free to @ me in a tweet about the post, but please keep my real name linked to GitHub. Thank you!

**Comment by maelle** [comment]
Found you! :wink:

**Pull request merged**
