### PR TITLE
docs URL?

### LINKED ISSUE #535: Add docs URL to packages table
Cc @jeroen

### PR DESCRIPTION
**Pull request by maelle**
To fix #535

### CODE REVIEW

**Comment by maelle** [comment]
@jeroen With this the packages page wouldn't link to GitHub repos directly at all, is that an issue in your opinion?

As noted above we wouldn't merge this if ropenscilabs packages remain in the registry.

**Comment by jeroen** [comment]
I don't think this is a problem because the docs page has a link to the git repository.

**Comment by maelle** [comment]
ok so should we merge this?

**Comment by jeroen** [comment]
Yes I think so. There are still a few packages that don't have docs because they fail to build, but those are mostly abandoned packages that we should probably archive soon.

**Pull request merged**
