### PR TITLE
add technote about precalc

### PR DESCRIPTION
**Pull request by jeroen**

### CODE REVIEW

**Comment by maelle** [comment]
Would it make sense to add synonyms to pre-calculate like pre-compile https://community.rstudio.com/t/precompiling-vignette-with-devtools/1583/2 pre-render, pre-generate? For SEO.

**Comment by jeroen** [comment]
Yes maybe that makes sense, I'm not quite sure what the correct terminology would be.

**Comment by jeroen** [comment]
This most is mostly so that we have a standard place we can point ropensci pkg authors to that are having trouble with the pkgdown docs.

**Comment by maelle** [comment]
I understood that and am very excited about it since I will be able to link to it from the dev guide.

Could you add sthg about strategies to remember to run precompile.R once in a while?

**Comment by maelle** [comment]
I myself am not sure about terminology but since the script is called precompile.R in at least eia and nasapower, the verb must make sense. 🙂

**Comment by jeroen** [comment]
I think they copied the `precompile.R` scrips from jsonlite, but I forgot why I named it that way. I didn't think about it very much :)

**Comment by maelle** [comment]
Ah ok. Tbh I found precalculate weird but it does make sense 🤷‍♀️

**Comment by jeroen** [comment]
I changed it in precompute now haha. I'm not sure if there is a good word for this.

**Pull request merged**
