### PR TITLE
Remove rwbclimate usecase

### PR DESCRIPTION
**Pull request by sckott**
we talked about removing this rwbclimate use case - as the pkg is broken

### CODE REVIEW

**Comment by maelle** [comment]
I think you forgot to remove it https://deploy-preview-608--ropensci.netlify.com/tutorials/rwbclimate_tutorial/

**Comment by sckott** [comment]
that's the tutorial, the use case is removed. 
i can remove the tutorial too though

**Comment by maelle** [comment]
:woman_facepalming: ah sorry. Yes I think removing both makes sense at the moment.

**Comment by sckott** [comment]
tutorial removed

**Pull request merged**
