### PR TITLE
change headers

### PR DESCRIPTION
**Pull request by maelle**
without messing with the encoding this time?

cf #30 and #278

### CODE REVIEW

**Comment by maelle** [comment]
@sckott if we merge this we'll lose your formatting of links. Is that bad?

**Comment by maelle** [comment]
Example of a bad change https://github.com/ropensci/roweb2/pull/279/files#diff-8828c4570d80dd504322aabbe30964f0L267 (this is a variable name that should have been escaped with backquotes)

**Comment by maelle** [comment]
As a reminder from my previous bad PR, changes that happen on top of header homogeneization are homogeneization of the Markdown syntax, 

* e.g. all item lists now made with "-", 

* lines with "***" and not a single star more.

* Some characters are also escaped e.g. https://github.com/ropensci/roweb2/pull/279/files#diff-0c00281f91e65f87d8337d8fb9d55bc8R25 resulting in a correct post https://deploy-preview-279--ropensci.netlify.com/blog/2013/03/14/ropensci-challenge/

* Links changed as mentioned above (no more [][] syntax with links at the bottom cf e.g. https://github.com/ropensci/roweb2/pull/279/files#diff-75fe62a662932365a6f315b63be72a6aL85 resulting in https://deploy-preview-279--ropensci.netlify.com/blog/2013/10/08/shutdown/, correct URL)

**Comment by maelle** [comment]
And to show the actual good stuff, see https://deploy-preview-279--ropensci.netlify.com/blog/2018/09/04/birds-taxo-traits/ vs https://ropensci.org/blog/2018/09/04/birds-taxo-traits/ , the new post uses h2 and h3 instead of h3 and h4.

**Comment by maelle** [comment]
Post using h1 at the moment https://ropensci.org/blog/2013/05/16/pyopensci/

In my branch it's  https://deploy-preview-279--ropensci.netlify.com/blog/2013/05/16/pyopensci/

@jeroen I still find h2 a bit big, but this could be changed in the style files, at least with my changes we'd have h2/h3/h4 everywere.

**Comment by sckott** [comment]
>  if we merge this we'll lose your formatting of links.

can  you show me an example. not sure what you mean

**Comment by maelle** [comment]
Sorry it's the 4th item in https://github.com/ropensci/roweb2/pull/279#issuecomment-422033172 (with links to examples)

**Comment by sckott** [comment]
I think we have to support markdown links with `[][]` as it's a standard markdown thing. or maybe others disagree?

**Comment by maelle** [comment]
What do you mean by supporting?

They get lost by this conversion but in the future we will hopefully not need to re homogeneize all header levels.

**Comment by sckott** [comment]
Does this PR make any changes to how posts are rendered moving forward, or just changes to posts in the past?

**Comment by maelle** [comment]
Just posts in the past. The unwanted changes in Markdown files in this PR (i.e changes other than header levels) are losses but should not change the resulting html.

I guess it's not impossible that we do such a batch edit again one day, but maybe it won't happen.

**Comment by sckott** [comment]
Okay, no worries then, just wanted to check if this was a change to how posts are rendered with hugo moving forward

**Comment by maelle** [comment]
will make a new PR once https://github.com/ropenscilabs/tinkr/issues/4 is solved :-)

**Pull request closed without merging**
