### PR TITLE
NOT TO BE MERGED my registry experiments

### PR DESCRIPTION
**Pull request by maelle**

### CODE REVIEW

**Comment by maelle** [comment]
Next steps for me:
* add repo status filtering (status is either repostatus.org badge or a simple deduction ropenscilabs -> WIP, ropensci -> Active) -- do not show abandoned etc.
* add status as a column
* add reviewed as a column
* add categories back/improve them
* have the JSON deployed somewhere more automatically

**Comment by jeroen** [comment]
I just adapted from an example until it worked. If you can improve the code, go for it 🚀💁

**Comment by maelle** [comment]
Cool, my main motivation will be to make this PR independent from #295 (where I deleted packages.html in favour of packages.md + a packages.html partial).

**Comment by maelle** [comment]
Thanks @jeroen, I've copy pasted from https://datatables.net/reference/option/columns.title and it worked :tada:

**Comment by maelle** [comment]
Next steps:

* Find a way to add filtering by status/onboarded while keeping the badges. 

* Maybe order by something else that alphabetically, or filter active repos by default (currently one of the first repos is "concept").

**Comment by maelle** [comment]
:eyes: https://datatables.net/manual/data/orthogonal-data ✨

**Comment by maelle** [comment]
The next step will be to limit the general search bar to package name, description and keywords, and to add filtering by status/onboarding, cran/bioc and maybe by maintainer (the fact that clicking on a name filters the table isn't intuitive)

**Comment by maelle** [comment]
https://datatables.net/examples/api/multi_filter_select.html

**Comment by maelle** [comment]
Also to be done:
- remove the CRAN badges when the package isn't on CRAN.
- make the badge less neon because of its being near other green badges (repostatus.org, peer-review)

**Comment by maelle** [comment]
Instead of using badges for peer-review and repo status I should defined label classes like the CRAN/bioc one, with the same colors and links as the repostatus.org badges, but smaller and without "Repo status" since it takes space and the column name already states it's status.

**Comment by maelle** [comment]
From Carl "doesn’t look like I can apply the check-box filters to the search results.  e.g. if I search for Chamberlain and then check CRAN box, I get no results. If I check Taxonomy and then search for Chamberlain, Taxonomy becomes un-checked"

**Comment by maelle** [comment]
_I_ am ok with the result now. 

Anyway this can only be merged once we use the new registry generation, since the current JSON doesn't have all the necessary information.

**Comment by maelle** [comment]
I'll rebase once #293 is merged (after which packages.html will be a partial)

**Comment by maelle** [comment]
From Carl : Minor issue: looks like I can now use the search bar to ‘refine’ a filter (e.g. click some filters first and then search), but if I do the reverse (search and then click filters) it clears my search.

**Comment by maelle** [comment]
Will try to fix next week @jeroen, thanks for the review!

**Comment by jeroen** [comment]
# Search box

screen shot 2018-10-18 at 6 01 14 pm


# Table alignment:

screen shot 2018-10-18 at 6 01 19 pm


# Paging numbers:

screen shot 2018-10-18 at 6 01 25 pm

**Comment by maelle** [comment]
Ok @jeroen I fixed:
* the search box width
* the alignment of the table and radio buttons
* the numbering style
_by loading libraries in the right order_ :woman_facepalming:

I removed the free text search on the package name, maintainer and description columns. I still think it's more intuitive to have filtering on status, peer-review and CRAN/Bioc under the column names than over the table, but we can debate this later. Thanks again for your comments!

**Comment by maelle** [comment]
One thing that I question myself is how to make the CRAN status filterable but not searchable 🤔

**Comment by maelle** [comment]
Scrape my previous comment, when can only search "true" or "false" from the CRAN column, not "cran" anyway. However, one can search "active" but I'm not sure the names of the statuses conflict with keywords one would use for a package search.

**Comment by maelle** [comment]
I am going to close this and start again, it'll be easier because of the conflicts I inserted + of the many changes.

What's good to keep:
* New URL for the JSON, information about onboarding, status.
* Definition of table column names in the JavaScript code
* Color of statuses, well until someone tells me to remove that 😸 

What needs to change:
* Peer-review should be an icon, grey or green, near the name of the page, with a link to the review, in details.
* Status should be filtered like CRAN/Bioc, with a button (just active vs all statuses). CRAN and status buttons will get their own row under category. By default filter active repos.
* Add examples to the search bar.

**Pull request closed without merging**
