### PR TITLE
thank you blog post

### PR DESCRIPTION
**Pull request by stefaniebutland**

### CODE REVIEW

**Comment by stefaniebutland** [comment]
numbers reported are taken from annual report results (Nov 1, 2018 to Oct 31, 2019) but Community Calls and use cases numbers are Jan - Dec 2019

Should I change the latter set?

**Comment by sckott** [comment]
i quickly counted no. of pkgs. looks like 31
for reviewers, i didn't count them, but a safe estimate would be 31 * 2

**Comment by stefaniebutland** [comment]
> do we thank funders here? i imagine not, but thought i'd ask

no

> we could include number of people that opened issues in our repos (non-code contributors) - do you want that?

sure. yes please if you have time

**Comment by stefaniebutland** [comment]
holy cow
made date-range for community calls match that for the other data

7 calls attended by people from 23 countries! 
US, Canada, Argentina, Netherlands, Switzerland, UK, China, France, Netherlands, Germany, Uruguay, Ireland, South Africa, Brazil, Hungary, India, New Zealand, Costa Rica, Senegal, Mexico, Poland, Belgium, Portugal

**Comment by sckott** [comment]
nice on the new comm calls data

**Comment by sckott** [comment]
> sure. yes please if you have time

by when do you need it?

**Comment by stefaniebutland** [comment]
@sckott if you gave me a number for `number of people that opened issues in our repos` by ~noon Friday ... or noon Sunday that's great

I think it's best for me to combine numbers of contributors because I don't want it to be a big list of smaller numbers, so this sentence: 
 
> contributed some code or documentation to a package (117 people made their first code contribution to rOpenSci this year)

would become:

> contributed some code or documentation to a package, or opened an issue in our repos (number)

where Number = ([Total number of contributors in the report period: 284](https://github.com/rosadmin/annual-reporting/issues/25#issuecomment-550778575)) - (number of paid staff code contributors: 4) + (number of people that opened issues in our repos) - (number of paid staff contributors: 5) 

staff code contributors: Scott Jeroen Karthik Maëlle
staff who opened issues: add me

Does that make sense?

**Comment by sckott** [comment]
hmm, i was thinking two numbers: code contribs and non-code contribs - you're suggesting to combine them?

agree, that we subtract staff from those numbers

**Comment by stefaniebutland** [comment]
>  two numbers: code contribs and non-code contribs

Sounds good!!

**Comment by sckott** [comment]
okay

**Comment by sckott** [comment]
@stefaniebutland i ran out of time. i can't get that other number, that okay?

**Pull request merged**
