### PR TITLE
draft /about/#team for feedback

### PR DESCRIPTION
**Pull request by stefaniebutland**

### CODE REVIEW

**Comment by maelle** [comment]
Agree about the editors

**Comment by stefaniebutland** [comment]
@maelle what do you mean about editors?

**Comment by maelle** [comment]
That it looks odd not to list affiliation for editors who are staff

**Comment by sckott** [comment]
For headings, perhaps remove **Our** from beginning of each of them?  Cause I guess it's already implied by being on this page.

**Comment by maelle** [comment]
Editors -> Software review editors? Not clear otherwise

**Comment by stefaniebutland** [comment]
s/Stacy/Stacey

**Comment by jeroen** [comment]
It looks a bit odd that Karthik and Scott are there 3 times. Maybe the section `Leadership and Advisors` can just be `Advisors` where some people have the `Leadership` badge, just like in the `Staff` section, and then there is no need to list K & S again in that section.

**Pull request merged**
