### PR TITLE
Calendar experiments

### PR DESCRIPTION
**Pull request by maelle**
Note to self

* https://icalendar.org/validator.html

* Be especially careful reg. timezones!

Notes for @stefaniebutland. This is a minimal working and not feature-complete-yet example for a) having a fully automatic calendar b) integrating the commcalls to roweb2. cf #307 

* There are two new folders in contents, events/ and commcalls/. The Markdown files inside them are only made of YAML, with info related to the event. The commcalls events will have more fields (e.g. Vimeo URL once available). 
* https://deploy-preview-316--ropensci.netlify.com/commcalls/ could be a list of all commcalls, with the upcoming ones at the top (defined by comparing dateEnd to now). It could be made quite fancy and pretty.
* https://deploy-preview-316--ropensci.netlify.com/events/ is a list of upcoming events _including comm calls_, and there's a link to an iCal feed. https://deploy-preview-316--ropensci.netlify.com/events/index.ics that you can add to your Google calendar (add via URL) -> not sure yet whether it updated in Google calendar if the ics gets updated, I think so though.
* in the commcalls folder I've already put a past comm call and you see it doesn't show up. "upcoming" = at most 2 days before today.
* Each event/comm call should get a better template. I've already added an ics link for each event to make it easier to add to any calendar. E.g. https://deploy-preview-316--ropensci.netlify.com/commcalls/2018-11-15-imaging/index.ics
* The stuff in https://deploy-preview-316--ropensci.netlify.com/events could be made a partial and get called from community/.

With such a setup @stefaniebutland to update the info about events and comm calls you'd only edit the YAML in their Markdown files/create new Markdown files. If we set the website build to happen automatically daily, the info in the calendar would always be up-to-date.

I'd still need to define a partial that you could call from blog posts "where to find the rOpenSci team", with only two parameters (events from dateA to dateB).

### CODE REVIEW

**Comment by maelle** [comment]
Potentially, one could keep the public Google calendar and have it subscribe to the ics feed? 🤔

**Comment by maelle** [comment]
I'm trying to generate many things automatically from comm calls timedate (presentation of next call, URL for findyourtimezone) which is a bit dangerous.

**Comment by maelle** [comment]
Questions for @stefaniebutland 
* Does such a setup make sense? If it does, I could try and convert past / current events and comm calls. The few events I have in this PR at the moment were added by hand. 
* Would you like the commcalls list to be minimalist like the current one? The video embedding could happen in the pages of individual comm calls.
* Any wish for the YAML info? E.g. at the moment for events you sometimes have a long description ("Topic" of next comm call) and a short one (for the calendar as table and the Google calendar). Would you like to have both fields?

**Comment by maelle** [comment]
When the event is a comm call, the events list template should use put that in the title, for more clarity.

**Comment by stefaniebutland** [comment]
(not many) Answers for @maelle 
From reading this, seeing the previews, and poking around, I'm having a hard time picturing what the workflow and look would be, without seeing inside your brain. I think I need to request a walkthrough call.

> Would you like the commcalls list to be minimalist like the current one? The video embedding could happen in the pages of individual comm calls.

- I do really like the current minimalist look of past community calls. To me, it allows someone coming to this page to see different call topics at a glance. e.g. came to look at one, and notice another of interest

**Comment by maelle** [comment]
Ok!

The workflow would be creating and editing Markdown files only (with info in YAML fields), and the look, sthg you'd choose.

**Comment by maelle** [comment]
Note, since events have YAML, we could add tags to events, so they'd turn up in the tags pages. It makes sense for comm calls I think.

**Comment by maelle** [comment]
Regarding the comm calls page, I was thinking it could look like the technotes and the archive pages. So the comm calls page itself wouldn't have direct links to video etc, these would be in the page of each event. I tend to think it'd make the comm calls page cleaner? But I can imagine it means more clicking to get to the video/discussion etc which might not be loved. Alternatively the comm calls page could have the same info as the current one but as a table with a video column (with video icon) etc, to make it cleaner?

**Comment by stefaniebutland** [comment]
>  I was thinking it could look like the technotes and the archive pages.

I had the same thought. Important to have some internal visual consistency

**Comment by maelle** [comment]
Useful links
* https://en.wikipedia.org/wiki/ICalendar
* https://en.wikipedia.org/wiki/List_of_applications_with_iCalendar_support

**Comment by stefaniebutland** [comment]
For calendar fields, I've thought through use cases and try to give when, who, where, what 

**Types of events:** 
- community call
- unconf
- person giving talk at a conference (i.e. include talk title where possible)
- person giving an online talk (e.g. Scott did rOpenSci webinar for CDC, Maëlle did remote talk for LatinR followed by an in-person panel with Jenny Bryan, Laura Acion, Mauro Lepore)
- person participating in a workshop or conference but not giving talk (why list this? indicates we're out there working; someone might see this and want to meet up with rOpenSci person, ask them to give a local R-Ladies chapter talk, or might want to attend that conference based on this info)
- we do not list events in which we are not participating
- we do not list events in which a team member is not representing rOpenSci while there

**When**
- single day and time e.g. a community call, standalone seminar or meetup
- multi-day span for conference or workshop
- provide date, time, link to check timezones. 
  - I find listing day of the week helpful as a sanity check when manually adding to my calendar. Challenge with timezones would mean day of week would have to have a reference point, like Thursday 2018-11-01 in Berkeley, CA
  - also depending on how you are calculating/displaying I like the timezone abbreviation e.g. PST as a sanity check i.e. you're telling the reader what the reference point for the time is

**Who** 
- rOpenSci staff person, leadership member, editor, or person representing rOpenSci (e.g. officially Nick Tierney asked by rOpenSci to speak at R Korea and less officially but with endorsement and support: Julia Gustavsen at OpenCon Switzerland, Jennifer Thompson at R/Medicine) 
- speakers for a community call

**Where**
- city, US state or country
- (maybe) flag emoji is nice, with a globe emoji if it's an online event https://ropensci.org/blog/2018/09/21/ropensci-at-meetings/ but only if this is not ugly or cheesy and worth the effort and only if we continue to do things in various countries so we don't have a single flag repeated

**What**
- title of community call
- name of conference and link to it; talk title when available and link to abstract
- sometimes will have two rOpenSci people giving talks at same conference and we'd like to link to their title to their abstracts individually

For community calls, info comes in over time including:
example https://ropensci.org/blog/2018/10/05/commcall-oct2018/
- date, time
- title aka topic
- description 
- agenda (can go in description)
- speaker names
- speaker bios, with links to 1 to 3 of their online presences
- zoom deets
- resources: see examples in table http://communitycalls.ropensci.org/

**Comment by maelle** [comment]
Thanks @stefaniebutland! Should `type` be a YAML field?

The timezone would have to be provided for all events, sorry about that. Yes day of the week would be computed depending on the timezone. I'm still a novice of date formatting with Hugo, but I think I can create two strings like you do for comm calls (where you list 2 or 3 timezones, we could by default do that for PST, my own timezone 😎 , some Australian timezone + have the link to the handy website for finding one's timezone)

So for speakers/attendees, we should have in the YAML:
* name
* url
* bio
* twitter
* rOpenSci affiliation? Instead of that we could deduce it from config.toml (where we'd add editors in a separate vector), but the problem with that is that someone's rOpenSci affiliation might change over time, and the website gets rebuilt regularly.

Good point on having resources URL depending on the speaker for "normal" events (not comm calls).

Info coming over time is fine, I'll just need to make sure the template handles that nicely, and writes TBA or so for missing fields.

I 💙 the flag emoji idea as you can imagine! And I keep the idea of a map somewhere in my head. Probably in single events pages (look what I found https://github.com/simonfrey/hugo-leaflet :sparkles: ), not comm calls, and one below the calendar... Not a priority, but definitely nice to have, so events might get lontitude and latitude.

**Comment by maelle** [comment]
will do 2 PRs instead.

**Pull request closed without merging**
