### PR TITLE
Remove "technote" from authors

### PR DESCRIPTION
**Pull request by steffilazerte**
In the (list of technotes)[https://ropensci.org/technotes/] it looks like opentripplanner has "technote" as an author. I think this is in error?

### CODE REVIEW

**Comment by maelle** [comment]
wow good catch!

**Comment by steffilazerte** [comment]
Actually there are more. Let me get them all before merging... hopefully this isn't a feature I'm reporting as a bug?

**Comment by maelle** [comment]
no, it's probably a mistake I made somewhere... sorry. if there are too many, next week I can write a script to fix that?

**Comment by steffilazerte** [comment]
There aren't too many and I think I got them all, but can you just run through quickly and make sure I didn't change anything I shouldn't have? Some of the yamls were a bit weird

**Pull request merged**
