### PR TITLE
make RSS stuff like @jeroen wants

### PR DESCRIPTION
**Pull request by maelle**
* Custom joint RSS feed for blog and tech notes, full content
https://deploy-preview-337--ropensci.netlify.com/rbloggers/index.xml

* Summary RSS feed for blog, and for tech notes
https://deploy-preview-337--ropensci.netlify.com/blog/index.xml
https://deploy-preview-337--ropensci.netlify.com/technotes/index.xml

* No "rbloggers" page, it only outputs RSS https://deploy-preview-337--ropensci.netlify.com/rbloggers

* Redirect updated

* In head, ref to the custom RSS feed only. Adapted from https://gohugo.io/templates/rss/#reference-your-rss-feed-in-head Maybe we should always reference the RSS of the page, not the "rbloggers" one. 🤔

### CODE REVIEW

**Comment by maelle** [comment]
* Custom joint RSS feed for blog and tech notes, full content
https://deploy-preview-337--ropensci.netlify.com/blogs/index.xml

* Summary RSS feed for blog, and for tech notes
https://deploy-preview-337--ropensci.netlify.com/blog/index.xml
https://deploy-preview-337--ropensci.netlify.com/technotes/index.xml

* No "blogs" page, it only outputs RSS https://deploy-preview-337--ropensci.netlify.com/blogs

**Comment by maelle** [comment]
Am also looking at https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fdeploy-preview-337--ropensci.netlify.com%2Fblogs%2Findex.xml 🕵️‍♀️

**Comment by jeroen** [comment]
> Maybe we should always reference the RSS of the page, not the "rbloggers" one. 🤔

Yes i think so too. the rbloggers feed is only for rbloggers, we should not advertise it.

**Comment by jeroen** [comment]
Awesome!

**Pull request merged**
