### PR TITLE
Trying new Chroma style

### PR DESCRIPTION
**Pull request by maelle**
In this PR preview you can see the fruity style that was mentioned by @sckott. Its colors are too bright I think? Edit: I put friendly in the preview. :angel: (the colors in fruity were really bright)

To try out another style from [the Chroma gallery](https://xyproto.github.io/splash/docs/longer/all.html) you can check out this PR locally and change the lines

```toml
  [markup.highlight]
    style = "friendly"
```

in config.toml

I've just tried "friendly" that I think looks great, but then I chose it for the R-hub blog. I don't mean we couldn't have the same, just that I have a bias.

Sadly monokai has too dark comments, I should actually change it on my own site.

Anyway, time to choose a style. :sparkles:

### CODE REVIEW

**Comment by maelle** [comment]
There's still #667 but it's not a default Chroma style and I'm not sure I correctly translated from hljs CSS to Chroma CSS classes.

**Comment by maelle** [comment]
I'm planning to change highlighting styles when #666 gets merged (nice PR number right). At the moment that PR chose "friendly".

Note that in the tech note of that PR I added a button to switch to dark mode https://deploy-preview-666--ropensci.netlify.app/technotes/2020/04/30/code-highlighting/ Maybe that's the perfect compromise? :slightly_smiling_face:

**Comment by karthik** [comment]
This style in the current deploy preview looks good to me

image

**Comment by maelle** [comment]
Cool. 

I'm a bit disappointed by my change because even after increasing font size https://color.a11y.com/Contrast/ tells me https://deploy-preview-666--ropensci.netlify.app/technotes/2020/04/30/code-highlighting/ has too low contrast for some code color pairs. :sob:

**Comment by maelle** [comment]
I wonder whether the _font_ is also a factor.

**Comment by karthik** [comment]
There will be a fixed width font in the css. Not quite sure what it is but it would be easy to swap around.

**Comment by maelle** [comment]
What do you mean by "there will be"?

**Comment by karthik** [comment]
There will be means a fixed width font for code/pre is defined somewhere in
the css. I don't have access to it yet.

**Comment by maelle** [comment]
Thanks, I'll explore that! :mag:

**Comment by maelle** [comment]
In the console, I don't see any fixed width applying to the elements when I select them. I'll need to explore further.

**Comment by maelle** [comment]
I thought a bit more and realized the problem lies with the contrast checker. The colors of that highlighting theme are actually partly bad, but that wasn't flagged on the R-hub blog because it uses in-line styling for code blocks as opposed to CSS classes + stylesheet.

So I'll need to try out more light themes. :upside_down_face:

**Comment by maelle** [comment]
https://maxchadwick.xyz/blog/syntax-highlighting-and-color-contrast-accessibility

https://blog.codepen.io/2019/09/09/new-high-contrast-syntax-highlighting-themes/

**Comment by maelle** [comment]
Ok, see new preview https://deploy-preview-666--ropensci.netlify.app/technotes/2020/04/30/code-highlighting/ :upside_down_face: (I followed the approach of https://maxchadwick.xyz/blog/syntax-highlighting-and-color-contrast-accessibility, we might want to switch to the approach https://blog.codepen.io/2019/09/09/new-high-contrast-syntax-highlighting-themes/ i.e. professional help later.

**Pull request closed without merging**
