### PR TITLE
taxaDB blogpost submission 

### PR DESCRIPTION
**Pull request by karinorman**

### CODE REVIEW

**Comment by karinorman** [comment]
@stefaniebutland I couldn't get any of the links to work for downloading the template, nor did installation via `roblog` work, so I modified a previous post's file, but it looks like I'm missing something that's making Hugo grumpy. Are the links on the `roweb2` readme to the markdown files working for you? I'm happy to convert to the template file if I can get access to it!

**Comment by stefaniebutland** [comment]
@karinorman I'm so sorry for the broken links. We have been re-writing blog guidelines from scratch and I (foolishly) did not realize I was breaking some existing links.

I will have a look at your post file shortly.

**Comment by stefaniebutland** [comment]
Here's link to the Rmd template: https://github.com/ropensci-org/blog-guidance/blob/master/templates/post-template.Rmd

fyi, The docs in that repo are WIP, but maybe this template will help.

**Comment by karinorman** [comment]
@stefaniebutland Thanks so much for the template! Made some changes after comparing the two but no luck, I'll keep poking around.

**Comment by stefaniebutland** [comment]
I'll get some help to troubleshoot and will let you know how to fix. (If I respond on the weekend, I don't expect you to respond outside your own work time.)

**Comment by maelle** [comment]
I am to blame for the missing templates, I am sorry! The current error is due to the presence of the setup code chunk in the .md. @karinorman do you want to write this post in R Markdown? If so you can rename it as Rmd and knit it. If not you can delete the setup chunk.

**Comment by stefaniebutland** [comment]
Here's the preview of your post @karinorman. It worked :-)
https://deploy-preview-609--ropensci.netlify.com/blog/2020/02/14/taxadb/

And it links to your author page https://deploy-preview-609--ropensci.netlify.com/authors/kari-norman/

This **work-in-progress** gitbook ["rOpenSci Blog Guidelines for Authors and Editors"](https://ropensci-org.github.io/blog-guidance/) might help you review your post, and I'm available on Slack for questions.

Please tag me when you're finished editing and ready for me to do a full review.

**Comment by karinorman** [comment]
@stefaniebutland I changed over to the .Rmd format because the rendering from the .md wasn't hiding code chunks with `echo = FALSE` or rendering my `DT` tables, but it looks like the post isn't up on the preview now. Is there something more I need to do for the .Rmd format? 

Also - happy to chat on slack but I don't think I'm on the rOpenSci channel yet. 

Thank you to both you and @maelle for helping me get this sorted!

**Comment by karinorman** [comment]
Ok @stefaniebutland, I'm happy with where the post is at! I fixed the little things you mentioned on the call, and I'll look out for further comments.

**Comment by karinorman** [comment]
Ok @stefaniebutland I think it's ready for the final review! Thanks so much for your helpful edits and suggestions (and kind words :) ).

**Comment by karinorman** [comment]
@stefaniebutland  Whoops - must've gotten a little checkbox happy in Rstudio. Should be fixed now!

**Pull request merged**
