### PR TITLE
ORCID tech note

### PR DESCRIPTION
**Pull request by maelle**
Direct link to preview https://deploy-preview-286--ropensci.netlify.com/technotes/2018/10/08/orcid/

### CODE REVIEW

**Comment by cboettig** [comment]
This is great!  A few quick comments for now:

- A bit more background on ORCID, not everyone might know these in published papers.  Maybe even a screenshot of a pdf / paper showing ORCIDs.
- can we `include=FALSE` the `webshot` code chunks?  I think they interrupt the flow of the narrative.  
- Probably not worth effort, but it occurs to me it would be fun to get a sense of how many of the CRAN packages uploaded in the last year have adopted at least one ORCID id already?  

Maybe get a quick-take from @mfenner on the intro of ORCID here?

**Comment by mfenner** [comment]
This looks good to me. The only optional suggestion is to also mention GitHub usernames, as people might wonder. Why use ORCID ID instead GitHub username, can either one be used, etc.

**Comment by maelle** [comment]
Thanks both @cboettig @mfenner!

* I removed the `webshot` code from the post.

* I added two more sentences about ORCID, and the meaning of the acronym. In the conclusion I say CRAN using GitHub would be a topic for another time (I wrote "ideally via Keybase" :wink: ). I also mention the fact that everything about ORCID is declarative, correct? I've put a link to a GitHub issue requesting Keybase verification for ORCID.

* I'll see if the data about current use of ORCID on CRAN is easily accessible, I'm curious now. 🙀  And actually, being able to search ORCIDs would allow one to assess their identity hasn't been used by someone else? 🤔

**Comment by maelle** [comment]
@cboettig study over all CRAN packages added :wink:

**Comment by maelle** [comment]
@sckott well done 😸  (see tech note preview :wink: )

**Comment by maelle** [comment]
Thanks @cboettig!

**Pull request merged**
