### PR TITLE
Update config.toml

### PR DESCRIPTION
**Pull request by maelle**
cf #272 

Not sure whether the GA settings are too strict now.

### CODE REVIEW

**Comment by maelle** [comment]
And actually I need to disable Disqus.

**Comment by sckott** [comment]
thanks @maelle 

I'm not sure what these settings actually do. e.g. for Disqus, we have it disabled, but i still see disqus on the relavant blog posts e..,g https://deploy-preview-276--ropensci.netlify.com/blog/2017/01/09/sustaining-research-projects/ and https://deploy-preview-276--ropensci.netlify.com/blog/2017/02/02/unconf2017/

**Comment by sckott** [comment]
the help page https://gohugo.io/about/hugo-and-gdpr/ doesn't help much wrt what disabling or not does in practice

**Comment by maelle** [comment]
Weird and not well documented indeed.

https://github.com/search?l=TOML&q=privacy.disqus&type=Code didn't get me far at first glance and I won't have time to investigate before next week at the earliest.

**Comment by maelle** [comment]
I had forgotten to update Hugo in the PR, no wonder the config had no effect! This is embarrassing.

**Comment by maelle** [comment]
I still see Disqus though 🤔

**Comment by maelle** [comment]
The problem with disqus might be that it's hard-coded in the template for blog posts, instead of used via Hugo.

**Comment by sckott** [comment]
well, we were keeping disqus for older blog posts as some did have comments on them through that platform, then for newer posts we have Discourse - i don't remember what the cutoff date is.  We could decide to get rid of Disqus altogether and so older posts will just lose those comments

**Comment by maelle** [comment]
I'll tackle this in separate PRs e.g. one for tweets.

**Pull request closed without merging**
